name: Promote charm to default track, standard risk levels.

on:
  workflow_dispatch:
    inputs:
      destination-channel:
        description: 'Destination Channel, e.g. latest/candidate'
        required: true
        type: choice
        options:
          - 'latest/candidate'
          - 'latest/stable'
      origin-channel:
        description: 'Origin Channel, e.g. latest/edge'
        required: true
        type: choice
        options:
          - 'latest/edge'
          - 'latest/candidate'

jobs:
  promote-charm:
    name: Promote charm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release charm to channel
        uses: canonical/charming-actions/release-charm@2.4.0
        with:
          credentials: $${{ secrets.CHARMHUB_TOKEN }}
          github-token: $${{ secrets.GITHUB_TOKEN }}
          destination-channel: $${{ github.event.inputs.destination-channel }}
          origin-channel: $${{ github.event.inputs.origin-channel }}
