name: Promote charm to default track, standard risk levels.

on:
  workflow_dispatch:
    inputs:
      channel-promotion:
        description: 'Channel Promotion, e.g. latest/edge -> latest/candidate'
        required: true
        type: choice
        options:
          - 'latest/edge -> latest/candidate'
          - 'latest/candidate -> latest/stable'

jobs:
  promote-charm:
    name: Promote charm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set channels
        id: set-channels
        run: |
          channel_promotion="$${{ github.event.inputs.channel-promotion }}"
          origin=$(echo "$channel_promotion" | sed 's/ ->.*//')
          destination=$(echo "$channel_promotion" | sed 's/.* -> //')
          echo "DESTINATION_CHANNEL=$destination" >> $GITHUB_ENV
          echo "ORIGIN_CHANNEL=$origin" >> $GITHUB_ENV
      - name: Release charm to channel
        uses: canonical/charming-actions/release-charm@2.4.0
        with:
          credentials: $${{ secrets.CHARMHUB_TOKEN }}
          github-token: $${{ secrets.GITHUB_TOKEN }}
          destination-channel: $${{ env.DESTINATION_CHANNEL }}
          origin-channel: $${{ env.ORIGIN_CHANNEL }}
